### ISSUE TITLE
crash on failed socketIO.wait

### ISSUE THREAD

**Issue by elosoman** [Ax-LED/volumio-pirate-audio#11]
Seems these come more frequent than first observed ... I thought I would post until I can take a peek at the code. 

Thanks for your plugin ...

Traceback (most recent call last):
  File "./display.py", line 414, in <module>
    main()
  File "./display.py", line 409, in main
    socketIO.wait()
  File "/usr/local/lib/python2.7/dist-packages/socketIO_client/__init__.py", line 251, in wait
    self._process_packets()
  File "/usr/local/lib/python2.7/dist-packages/socketIO_client/__init__.py", line 278, in _process_packets
    self._process_packet(engineIO_packet)
  File "/usr/local/lib/python2.7/dist-packages/socketIO_client/__init__.py", line 491, in _process_packet
    delegate(parse_socketIO_packet_data(socketIO_packet_data), namespace)
  File "/usr/local/lib/python2.7/dist-packages/socketIO_client/__init__.py", line 513, in _on_event
    namespace._find_packet_callback(event)(*args)
  File "./display.py", line 301, in on_push_state
    el_time = int(float(args[0]['seek'])/1000)
TypeError: float() argument must be a string or a number

**Comment by elosoman** [comment]
restarting display.py (or reboot) seems to make it work again.

**Comment by elosoman** [comment]
sorry ... i see that this is now part of volumio.
